###
GET http://localhost:3000/abrageo/pedidos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJIb3R0b3N0b29scyIsImRpc3RyaWJ1aWRvciI6IkhvdHRvc3Rvb2xzIiwicHJvZmlsZSI6NSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2MTg5MzQ2NjV9.QpeyPl8nGyTeHqC0GuBjxE0AlijSWzklZhQZPqtzNjw


###
GET http://localhost:3000/abrageo/pedidos/pdf/12 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJIb3R0b3N0b29scyIsImRpc3RyaWJ1aWRvciI6IkhvdHRvc3Rvb2xzIiwicHJvZmlsZSI6NSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2MTg1OTUxMTh9.5AvTTkIRG6q5iXdAAa_HKeNDJekQ5xIvY95FNlgjO2E

###
GET http://localhost:3000/abrageo/pedidos/detalle/orden/12 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJIb3R0b3N0b29scyIsImRpc3RyaWJ1aWRvciI6IkhvdHRvc3Rvb2xzIiwicHJvZmlsZSI6NSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2MTg5MzQ2NjV9.QpeyPl8nGyTeHqC0GuBjxE0AlijSWzklZhQZPqtzNjw

###
GET http://localhost:3000/abrageo/pedidos/asesor/distri HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJIb3R0b3N0b29scyIsImRpc3RyaWJ1aWRvciI6IkhvdHRvc3Rvb2xzIiwicHJvZmlsZSI6NSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2MTkwMzUyNDR9.WMUoJwdYMsB2Sq2nqVRUy4uFUFfTcU3DRDAzdoYCf4M