###
POST    http://localhost:3000/abrageo/statistic/distributor/Lineal HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJIb3R0b3N0b29scyIsImRpc3RyaWJ1aWRvciI6IkhvdHRvc3Rvb2xzIiwicHJvZmlsZSI6NSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2MTkyMTE0OTR9.Ycx_3H9sfP8ELK_E9631x7ioE4R1vv9AKzrE4wyUXA4
content-type: application/json

{
    "fecha": "2020-04"
}

###
GET   http://localhost:3000/abrageo/statistic/distributor/Pie HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSG90dG9zdG9vbHMiLCJwcm9maWxlIjo1LCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTYxODQyNTQzM30.6-nQzifoXnmSfkWqHPeWCOw75TLm6PUcY6243gNgY8c