###
POST    http://localhost:3000/abrageo/statistic/distributor/Lineal HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJtYXRlbyIsImRpc3RyaWJ1aWRvciI6IkFCUkFDT0wiLCJwcm9maWxlIjoxLCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTYxOTQ0NjA1Nn0.vFHRAvhRL7l_xvmdFJUD0olyyqIZE7SM_w-AT3puMpY
content-type: application/json

{
    "fecha": "2021-04"
}

###
GET   http://localhost:3000/abrageo/statistic/distributor/Pie HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSG90dG9zdG9vbHMiLCJwcm9maWxlIjo1LCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTYxODQyNTQzM30.6-nQzifoXnmSfkWqHPeWCOw75TLm6PUcY6243gNgY8c

###
GET   http://localhost:3000/abrageo/statistic/distributor/States HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc2Vzb3IiOiJtYXRlbyIsImRpc3RyaWJ1aWRvciI6IkFCUkFDT0wiLCJwcm9maWxlIjoxLCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTYxOTQ0NjA1Nn0.vFHRAvhRL7l_xvmdFJUD0olyyqIZE7SM_w-AT3puMpY


