###
GET http://localhost:3000/abrageo/users HTTP/1.1

###
POST http://localhost:3000/abrageo/users HTTP/1.1
Content-Type: application/json

{
    "asesor":"juan",
    "distribuidor":"Hottostools", 
    "email":"juan@correo.com",
    "password":"123456",
    "profile":4
}